[dependencies]
base = "0.11.1"
matchers = "https://github.com/kritzcreek/motoko-matchers#v1.3.0"
encoding = "https://github.com/aviate-labs/encoding.mo#v0.4.1"
io = "https://github.com/aviate-labs/io.mo#v0.3.2"
uuid = "https://github.com/fury02/uuid.mo#v0.2.0"
canistergeek = "https://github.com/usergeek/canistergeek-ic-motoko#v0.0.7"
map = "9.0.1"
stablebuffer = "https://github.com/canscale/StableBuffer#v1.3.0"
prng = "0.0.3"